name: Auto Renew (Strict Login)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run_strict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 安装字体 (防止方框乱码)
    - name: Install System Fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install playwright pyotp
        playwright install chromium

    - name: Run script
      env:
        DIS_EMAIL: ${{ secrets.DIS_EMAIL }}
        DIS_PASSWORD: ${{ secrets.DIS_PASSWORD }}
        DIS_SECRET: ${{ secrets.DIS_SECRET }}
      run: python -u main.py

    # 只要有任何图片生成，都上传给我看
    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-evidence
        path: "*.png"
        retention-days: 3
