name: Auto Renew Server

on:
  workflow_dispatch: # 允许你手动点击按钮运行
  schedule:
    - cron: '0 1 * * *' # 每天 UTC 时间 01:00 运行 (相当于北京时间早上9点)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install playwright pyotp
        playwright install chromium

    - name: Run script
      env: # 将 GitHub 里的密码传入脚本
        DIS_EMAIL: ${{ secrets.DIS_EMAIL }}
        DIS_PASSWORD: ${{ secrets.DIS_PASSWORD }}
        DIS_SECRET: ${{ secrets.DIS_SECRET }}
      run: python main.py
